import type { AgentName } from '../types/stream.types';

export const TOOL_TO_AGENT: Record<string, AgentName> = {
  findCase: 'reasoner',
  getCaseGraphContext: 'reasoner',
  getCaseOverview: 'reasoner',
  getCaseEvidence: 'reasoner',
  getCaseDocuments: 'reasoner',
  getCaseCommunications: 'reasoner',
  findSimilarCases: 'reasoner',
  rankSimilarCasePairs: 'reasoner',
  findSameStageLeaders: 'reasoner',
  getReadinessSignals: 'reasoner',
  getCaseInjuryProfile: 'reasoner',
  getStageTimeline: 'reasoner',
  getObservedStageTransitions: 'reasoner',
  benchmarkAgainstStage: 'reasoner',
  searchCases: 'reasoner',
  portfolioAggregates: 'reasoner',
  listPortfolioContacts: 'reasoner',
  listPortfolioExperts: 'reasoner',
  rankCasesByStageTransitionTime: 'reasoner',
  deriveReadinessPattern: 'reasoner',
  compareCaseToReadinessPattern: 'reasoner',
  estimateTimeToStage: 'reasoner',
  runReadOnlyCypher: 'reasoner',
  'get-schema': 'reasoner',
  'read-cypher': 'reasoner',
};

export const TOOL_LABELS: Record<string, string> = {
  findCase: 'Resolve case',
  getCaseGraphContext: 'Case graph context',
  getCaseOverview: 'Case overview',
  getCaseEvidence: 'Evidence summary',
  getCaseDocuments: 'List documents',
  getCaseCommunications: 'Case communications',
  findSimilarCases: 'Similar cases',
  rankSimilarCasePairs: 'Similar case pairs',
  findSameStageLeaders: 'Same-stage reference cases',
  getReadinessSignals: 'Auxiliary case metadata',
  getCaseInjuryProfile: 'Injury profile',
  getStageTimeline: 'Stage timeline',
  getObservedStageTransitions: 'Observed stage transitions',
  benchmarkAgainstStage: 'Stage benchmark',
  searchCases: 'Search cases by filters',
  portfolioAggregates: 'Portfolio aggregation',
  listPortfolioContacts: 'Portfolio contacts',
  listPortfolioExperts: 'Portfolio experts',
  rankCasesByStageTransitionTime: 'Stage transition timing',
  deriveReadinessPattern: 'Historical readiness pattern',
  compareCaseToReadinessPattern: 'Case vs readiness pattern',
  estimateTimeToStage: 'Estimate time to stage',
  runReadOnlyCypher: 'Read-only Cypher',
  'get-schema': 'Neo4j schema',
  'read-cypher': 'Neo4j read query',
};
