export const DEFAULT_CASE_REASONER_SYSTEM_PROMPT = `
You are a case reasoning assistant for an Israeli personal-injury case graph.

Use the available tools to answer questions from graph evidence. Resolve ambiguous case references with findCase before using case-scoped tools. For OCR, disability, ביטוח לאומי/NII, medical committee, missing document, next-step, income-impact, salary, Regulation 15, or case-value questions, use the OCR/fact/value tools before answering: searchDocumentEvidence, getCaseDocumentFacts, findComparableCasesByFacts, and/or getCaseValueContext. For medical concept case-listing questions such as neurological, orthopedic, spine/back/neck, nerve, EMG, disc, or radiating-pain concepts, use searchCasesByMedicalEvidence rather than exact injuryName/bodyPart filters. If the user asks to answer only from graph queries, explicitly restrict the answer to tool output and say when the graph has insufficient evidence. For valuation, separate observed facts, comparable-case ranges, missing evidence, and non-estimable items; never invent a precise value or disability percentage not returned by tools. For missing documents or next steps, derive from graph evidence: missingCritical, OCR required_document facts, and documents/facts present in comparable cases that progressed further.

For case-specific progression questions such as "what can move this case to כתב תביעה / filing / complaint and why", do not answer from readiness cohorts alone. Resolve the case, inspect current case overview/evidence/documents/OCR facts, then compare readiness if useful. If the target-stage readiness cohort is sparse, say that the historical pattern is sparse, but still report graph-backed current-case blockers and accelerators from missingCritical, document categories, OCR required_document facts, and concrete evidence already present. For pure readiness questions, choose the minimum tools needed: resolve the case, inspect the readiness pattern, compare the target case, and estimate timing only when timing is asked or needed. Cite cohort availability, historical peer count, estimation basis, matched signals, missing evidence signals, estimate, confidence, and uncertainty from tool output when those tools are used. If availability is sparse_stage or none, say there is no learned readiness cohort; report the low-confidence timing fallback or data gap instead of inventing missing checklist items. Treat contextDifferences as peer context, not as required missing evidence. Do not invent legal conclusions; state what the graph shows, what is missing, and what evidence supports the answer.

Do not add filters that are not entailed by the user's words. Omit caseType, phase, status, signed, overdue, date, boolean filters, and numeric filters unless the user explicitly asked for them. Never pass neutral defaults such as ageMin:0, ageMax:130, disabilityPercentMin:0, disabilityPercentMax:100, workAccidentFlag:false, or permanentDisability:false just to fill a schema. For getCaseCommunications, omit the direction parameter entirely unless the user used a direction word. Anti-examples (omit direction): "show communications on case X", "list emails for case X", "what messages are on this case". Examples that justify direction: "incoming emails on case X" → direction:"incoming"; "outgoing whatsapp on case X" → direction:"outgoing".

If a tool returns status:"filter_too_restrictive" with a diagnostic.appliedFilters field, retry the SAME tool with the filters narrowed to only those entailed by the user's words. Do not give up — the diagnostic explicitly tells you the graph has matching cases; the response was empty only because the filter combination over-narrowed. Drop legalStage, workAccidentFlag, permanentDisability, and disability percent bounds first when the user did not mention stage or disability. For caseType, when the user said "תאונת דרכים" / "car accident" without specifying severity, omit caseType and rely on the tool's seed-based or signal-based matching across both car-accident severities.

For follow-up questions asking for the most similar/comparable cases, use the last resolved case from the conversation as the seed if the user does not name a new case. Call findComparableCasesByFacts with that caseId and a limit, or findSimilarCases when readiness-signal similarity is requested. Do not substitute portfolioAggregates for comparable-case retrieval.

For comparative "which cases reached stage X fastest / leaders / shortest time to stage" questions across the portfolio (no seed case), use rankCasesByStageTransitionTime. Do NOT use sortBy:monthsSinceEvent as a proxy - that field measures time since the accident to today, not time taken to reach the stage. If the timing tool has no timed rows, state that true transition timing is unavailable and offer a clearly labeled proxy. When the rank tool returns allTimingFromSnapshotOnly:true (or any row with timingSource:"current_stage_snapshot"), surface that the duration measures case age at stage entry and not a measured transition.

No-proxy rule: if no available tool answers the user's question directly, say so. Never substitute a tangential aggregation (e.g. documentCategory counts for "experts", communications for "contacts", monthsSinceEvent for "time-to-stage") and present it as the answer. State the limitation, then optionally offer the closest related insight clearly labeled as a proxy.

Tool selection for entity counts vs. portfolio rollups: when the user asks "how many cases involve <named entity X>" use searchCases with the appropriate entity filter (e.g. {insurer:"X"}). Use portfolioAggregates only when the user asks for a distribution or rollup across all values of a dimension. For listing actual contact or expert names (lawyers, doctors, witnesses, our experts), use listPortfolioContacts or listPortfolioExperts; portfolioAggregates returns counts, not names. For "did the insurer initiate any thread" / "messages from the doctor", use getCaseCommunications with senderContactType — do NOT use the direction filter as a proxy for participant role.

Return concise answers with concrete case IDs, stage names, missing evidence, and caveats when data is incomplete. When listing cases, always include caseId. When tool output is truncated, state the returned count and total count if provided. Never use a literal "[...]" placeholder in the final answer; summarize omitted rows instead.
`.trim();

export const DEFAULT_TOOL_DESCRIPTIONS: Record<string, string> = {
  findCase:
    'Resolves a free-form reference TO ONE SPECIFIC CASE into ranked case candidates using canonical caseId, Mongo _id/sourceId, case number, case name, or client name. DO NOT use this tool for case-type categories or generic descriptions (e.g. "תאונת דרכים" / "car accident", "תאונת עבודה" / "work accident", or any caseType vocabulary value); those are scenario inputs for findComparableCasesByFacts, not case identifiers.',
  getCaseGraphContext:
    'Fetches the case graph context for a canonical caseId or Mongo _id/sourceId: current stage/substage, core related entities, signal snapshot, and graph counts.',
  getCaseOverview:
    'Fetches the core case summary, current stage, client, assigned experts (ours and court-appointed), document/communication/contact counts, projection metadata, and legal timing warnings for one canonical caseId or Mongo _id/sourceId.',
  getCaseEvidence:
    'Summarizes the case evidence graph by document category for one canonical caseId or Mongo _id/sourceId, with file examples and top case signal labels.',
  getCaseDocuments:
    'Lists documents for one canonical caseId or Mongo _id/sourceId, including category, type, OCR status, and provenance links when present. Omit category for all documents; do not pass an empty category.',
  searchDocumentEvidence:
    'Searches graph-indexed OCR chunks and extracted EvidenceFact nodes with full-text search. Use for free-text evidence, links, NII/ביטוח לאומי, medical committee, disability, salary, Regulation 15, missing document, or graph-only document-substance questions. Returns snippets, document IDs, chunk/fact IDs, categories, page ranges, and source links.',
  getCaseDocumentFacts:
    'Fetches OCR-derived structured facts for one case, grouped by kind: disability_period, regulation_15, nii_decision, appeal_deadline, required_document, income_evidence, medical_committee, and work_accident. Use before answering case-specific disability/NII/value/document-substance questions.',
  getCaseCommunications:
    'Lists recent communications for one canonical caseId or Mongo _id/sourceId, including direction, participant buckets, and preview text. By default returns ALL directions; pass the direction filter ONLY when the user explicitly asks for "incoming" or "outgoing" — never as a default. For "did <role> initiate any thread" / "messages from the <role>", use senderContactType (e.g. "insurance_company", "lawyer", "doctor"); this walks participant edges directly and is more accurate than the direction proxy.',
  findSimilarCases:
    'Finds graph-derived similar cases based on overlapping readiness signals, with human-readable reasons.',
  findSameStageLeaders:
    'Returns peers currently in the same legal stage as the seed case, ranked by completion and current age. Use rankCasesByStageTransitionTime, not this tool, for portfolio "which cases reached stage X fastest" questions.',
  getReadinessSignals:
    'Fetches auxiliary readiness metadata for one caseId, such as projection completion, overdue flag, months since event, days since last communication, and covered document categories.',
  getCaseInjuryProfile:
    'Fetches the injury profile for one caseId, including main injury, injury nodes, and affected body parts.',
  getStageTimeline:
    'Fetches stage transition history for one caseId and the list of known stages in the graph. Use this to resolve exact stage names.',
  benchmarkAgainstStage:
    'Compares one case against peer cases that reached a target stage, including completion, timeline, document coverage quartiles, and peer examples. Use it for broad benchmarking, not as the primary readiness answer.',
  searchCases:
    'Searches cases with structured filters (type, stage, phase, status, signed/overdue, injuries, document categories, numeric bounds, dates) and sorting. Use this for "how many / which cases involve <named entity X>" — pass the matching filter (e.g. {insurer:"X"}, {injuryName:"X"}). For "most recent" use sortBy:"createdAt" sortOrder:"desc" limit:1; for "oldest open" use sortBy:"createdAt" sortOrder:"asc"; for "by accident date" use sortBy:"eventDate". DO NOT use sortBy:"monthsSinceEvent" as a "fastest to reach stage" proxy — it measures time since accident to today, not time-to-stage.',
  searchCasesByMedicalEvidence:
    'Finds cases by broad medical concepts using hybrid graph evidence: structured Injury/BodyPart nodes plus OCR DocumentChunk snippets. Use this instead of searchCases when the user asks to show/list cases with semantic medical concepts such as neurological injury, spine/back/neck, nerve symptoms, EMG, disc, radiating pain, orthopedic-neurologic overlap, or Hebrew variants. Returns case IDs, matched structured terms, source snippets, document IDs, and signal counts.',
  portfolioAggregates:
    'Aggregates the portfolio by legal stage, case type, phase, status, insurer, injury, body part, missing critical document, document category, contactType (counts contacts per role), or expertSide (ours vs court). Use only for distribution questions across all values of a dimension; for "how many cases involve <one named entity>" use searchCases instead.',
  listPortfolioContacts:
    'Lists deduped Contact nodes across the portfolio with case counts and caseIds. Filter by contactType (e.g. "lawyer", "doctor", "witness", "insurance_company") to answer "show me all the X". Set sharedAcrossCasesOnly:true to find contacts that appear in multiple cases. Returns names, not just counts — use this rather than portfolioAggregates when the user wants to see who the contacts are.',
  listPortfolioExperts:
    'Lists Expert nodes across the portfolio with per-side case counts (ours / court) and caseIds. Filter by side ("ours" | "court") or omit for both. Returns expert names and specialties — use this when the user asks "which experts do we work with".',
  findMostSimilarCasePairs:
    'Returns the top-N most similar Case PAIRS across the entire portfolio, ranked by the precomputed SIMILAR_TO edge score (Jaccard over readiness signals + cosine over case-summary embeddings). Use this for portfolio-wide "most similar cases" / "מי הכי דומה למי" / "the 2/N most similar cases I have" questions where the user did NOT name a seed case AND did NOT supply structured facts. Each result row is a {caseA, caseB} pair plus score and human-readable reasons; the user-facing "2 most similar cases" maps to limit:1 (one pair = two cases). Optional caseType filter restricts BOTH cases in each pair to the same type (e.g. caseType:"car_accident_minor"). Do NOT use this tool when the user names a specific case (use findSimilarCases or findComparableCasesByFacts with that seed instead).',
  findComparableCasesByFacts:
    'Finds comparable cases using a seed caseId and/or explicit structured graph-fact filters such as case type, work-accident flag, age band, injury/body part, disability percent range, permanent disability, stage, and existing similarity edges. For a known case or follow-up "similar cases" request, pass the seed caseId and omit neutral default filters; the tool derives overlap from seed facts. Use for scenario-only questions or when comparing a new/client scenario to graph evidence. For NO-SEED category-only queries (e.g. "show me 2 most similar car-accident cases" without naming a case), the tool requires SOME narrowing input to compute similarity — pass the user\'s category term in the `injury` field (e.g. injury="תאונת דרכים" / injury="car accident" / injury="תאונת עבודה") and the tool will auto-expand to all matching caseTypes (e.g. both car-accident severities). Without any seed, caseType, injury, or bodyPart, the tool cannot rank similarity and returns zero hits. When the response status is "filter_too_restrictive", read diagnostic.appliedFilters and retry with fewer filters; when status is "insufficient_graph_evidence" with a diagnostic.hint, follow the hint to retry.',
  getCaseValueContext:
    'Builds graph-backed value context from current case valuation, OCR-derived disability/income/NII facts, and comparable cases with valuation ranges. Use for "case value", "how much is it worth", "estimate compensation", disability-value, salary-impact, or NII deduction questions. Returns insufficient_graph_evidence when the graph cannot support a value answer.',
  rankCasesByStageTransitionTime:
    'Ranks portfolio cases by explicit transition timing to a target stage using REACHED_STAGE or legalStageEnteredAt plus eventDate. Use this for "which cases reached stage X fastest"; never use monthsSinceEvent for that intent. Output includes per-row timingSource ("activity_log" or "current_stage_snapshot"), plus top-level allTimingFromSnapshotOnly / activityLogHitCount / snapshotHitCount. When all rows are snapshot-sourced, the "days from event to stage" is case age at stage entry, not a measured transition — surface that caveat in the answer.',
  deriveReadinessPattern:
    'Selects the historical cohort that reached a target stage and returns common graph-derived signals plus cohort timing statistics. If no cohort exists, returns a structured sparse-stage result with peer count and uncertainty instead of failing. caseId is OPTIONAL — provide it for caseType-aware cohort selection; OMIT it when the user asks "what is the readiness pattern for stage X" without naming a specific case.',
  compareCaseToReadinessPattern:
    'Compares one case against a historical readiness cohort and returns matched evidence, missing evidence signals, context differences, provenance, and weighted coverage. If no cohort exists, returns a structured sparse-stage result and does not invent missing signals.',
  estimateTimeToStage:
    'Estimates remaining time to a target stage using similar historical cases from the selected cohort. If no cohort exists, falls back to direct stage timing peers with low confidence. Always report availability, peer count, estimation basis, confidence, and uncertainty.',
};

export function getDefaultToolDescription(toolName: string): string | null {
  return DEFAULT_TOOL_DESCRIPTIONS[toolName] ?? null;
}
